# Generated by Django 3.2.5 on 2021-11-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Switches',
            new_name='Device',
        ),
    ]
